#!/bin/sh
. /usr/local/share/portshaker/portshaker.subr
if [ "$1" != '--' ]; then
	err 1 "Extra arguments"
fi
shift
method="git"
git_clone_uri="https://github.com/vkarlsen/customports.git"
git_branch="master"
run_portshaker_command $*

